name:                cal-clone
version:             0.1.0.0
github:              "FourCredits/cal-clone"
license:             BSD3
author:              "Erik Grundy"
maintainer:          "erik.grundy@gmail.com"
copyright:           "2021 Erik Grundy"

extra-source-files:
- README.md
- ChangeLog.md

synopsis:            cal clone, written in Haskell, with Monday as the first day of the week
category:            Shell

description:         Please see the README on GitHub at <https://github.com/githubuser/cal-clone#readme>

dependencies:
- base >= 4.7 && < 5
- time >= 1.9
- split >= 0.2
- ansi-terminal >= 0.6
- boxes >= 0.1.5
- optparse-applicative >= 0.16

library:
  source-dirs: src

executables:
  mal:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - cal-clone

tests:
  cal-clone-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - cal-clone
